name: "Terraform Apply"
description: "Run terraform apply"

inputs:
  working_directory:
    description: "Path to terraform root directory"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      shell: bash
      run: terraform init
      working-directory: ${{ inputs.working_directory }}

    - name: Terraform Apply
      shell: bash
      run: terraform apply -auto-approve
      working-directory: ${{ inputs.working_directory }}
