name: Kubectl Deploy
inputs:
  manifests_path:
    required: true
  namespace:
    required: true
  image:
    required: true

runs:
  using: composite
  steps:
    - name: Ensure Namespace Exists
      shell: bash
      run: |
        kubectl create namespace ${{ inputs.namespace }} \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Apply Manifests
      shell: bash
      run: |
        kubectl apply -f ${{ inputs.manifests_path }} -n ${{ inputs.namespace }}

    - name: Update Image
      shell: bash
      run: |
        kubectl set image deployment \
          --all \
          *=${{ inputs.image }} \
          -n ${{ inputs.namespace }}
