name: "Terraform Plan"
description: "Run terraform plan"

inputs:
  working_directory:
    required: true
    
  client_id:
    required: true

  client_secret:
    required: true

  subscription_id:
    required: true

  tenant_id:
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      shell: bash
      run: terraform init
      working-directory: ${{ inputs.working_directory }}    

    - name: Terraform Validate
      shell: bash    
      run: terraform validate
      working-directory: ${{ inputs.working_directory }}

    - name: Terraform Plan
      shell: bash
      run: terraform plan
      working-directory: ${{ inputs.working_directory }}

