name: "Terraform Plan"
description: "Run terraform plan"

inputs:
  working_directory:
    description: "Path to terraform root directory"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      shell: bash
      run: terraform init
      working-directory: ${{ inputs.working_directory }}    

    - name: Terraform Validate
      shell: bash    
      run: terraform validate
      working-directory: ${{ inputs.working_directory }}

    - name: Terraform Plan
      shell: bash
      run: terraform plan
      working-directory: ${{ inputs.working_directory }}

