name: Docker Push
inputs:
  image:
    required: true
  tag:
    required: true
  acr_name:
    required: true

runs:
  using: composite
  steps:
    - name: Login to ACR
      shell: bash
      run: |
        az acr login --name ${{ inputs.acr_name }}

    - name: Tag & Push Image
      shell: bash
      run: |
        docker tag ${{ inputs.image }}:${{ inputs.tag }} \
          ${{ inputs.acr_name }}.azurecr.io/${{ inputs.image }}:${{ inputs.tag }}

        docker push ${{ inputs.acr_name }}.azurecr.io/${{ inputs.image }}:${{ inputs.tag }}
