name: Docker Push
inputs:
  image:
    required: true
  tag:
    required: true

runs:
  using: composite
  steps:
    - name: Login to ACR
      shell: bash
      run: |
        az acr login --name acr

    - name: Tag & Push Image
      shell: bash
      run: |
        docker tag ${{ inputs.image }}:${{ inputs.tag }} \
          acr.azurecr.io/${{ inputs.image }}:${{ inputs.tag }}

        docker push acr.azurecr.io/${{ inputs.image }}:${{ inputs.tag }}
